### ISSUE TITLE
Connect 10 sensors of it

### ISSUE THREAD

**Issue by prsolucoes** [monkeyboard/Wiegand-Protocol-Library-for-Arduino#1]
Hi,

I need connect 10 sensors with Wiegand protocol, but your library has a const for only one port. How i can connect 10 sensors using it?

**Comment by Apollon77** [comment]
Would is not be possible to remove the "hard coded" Pin definition from the header file (and the hard coded interrupt numbers in attachInterrupt calls and offer a second begin-method-definition with 4 parameters (pinD0,intNrD0,pinD1,intNrD1) so that everything can be set dynamically.
Then it should be possible to simply have up to X (in this case mainly for the available external interrupts) objects in the own code.

If wanted I can also try to change the library that way when I do the coding for my fingerprint reader :-)

**Comment by jpliew** [comment]
The code was originally designed for UNO and there are only two pins available. So I did not make the code more complicated by having a user definable parameters. Maybe it is a good idea to improves @ugge75 's version of the library.

**Comment by Apollon77** [comment]
Hm ... that would mean (my opinion) to create a new fork of your version just for adding this  little code/possibility to configure the pins and interrupts. @ugge75 's version of the library (sorry to say that) made it more complex by just duplicating nearly all lines of your code two times ... this is the "hammer method" to solve the problem to have more then one fingerprint-reader :-(

**Comment by traningmicros** [comment]
hola muy buenas tardes, estoy tratando teniendo problemas con la biblioteca de wiegand 2560mega, se quedan congelados los teclados luego de un tiempo, solamente conecte dos y el otro dejo los pines a +vcc con una resistencia de 220 ohm alguien sabe que pasa con esta libreria

**Comment by Thiagodcfarias** [comment]
Hi, 
i can get the serial number of my RFID using the example in this library. However, i´m missing the first bit of serial number and i don´t know how to fix it. 

My RFID use 34 bits, 32 for serial number and 2 for parity, but when i code "Serial.print(wg.getCode(),BIN);" i recieve just 31 bits :(
